name: Bug Report
description: Report a bug or issue you've encountered
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened instead
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images or paste URLs here

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Edge
        - Brave
        - Opera
        - Other Chromium-based browser
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., 120.0.0.0
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of BrowsePing are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS Sonoma (14.x)
        - macOS Ventura (13.x)
        - macOS Monterey (12.x)
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Other Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - When did this issue start occurring?
        - Can you reproduce it consistently?
        - Any error messages in the console?

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: If you have an idea for how to fix this, please describe it here (optional)
      placeholder: Your suggested fix or workaround

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: This is not a security vulnerability (I understand I should use SECURITY.md for that)
          required: true
        - label: I have provided clear reproduction steps
          required: true
        - label: I have included relevant screenshots or error messages (if applicable)
          required: false
