name: Feature Request
description: Suggest an idea to improve BrowsePing
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what feature or improvement you'd like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this feature be useful? Describe the problem it solves or the benefit it provides
      placeholder: Explain why this feature is needed...
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Explain what currently happens and why it's not ideal
      placeholder: What happens now?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you would like this feature to work. Be as detailed as possible
      placeholder: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you considered any other ways to solve this problem? (optional)
      placeholder: Other approaches you've considered...

  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: If applicable, add examples, mockups, or screenshots that illustrate your feature request
      placeholder: Drag and drop images or paste URLs here

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Does this relate to any existing issues? (e.g., #123)
      placeholder: "#123, #456"

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would this feature impact the BrowsePing experience?
      options:
        - Minor enhancement
        - Moderate improvement
        - Major feature
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or information that might be helpful
      placeholder: Any other details...

  - type: checkboxes
    id: checklist
    attributes:
      label: Before Submitting
      description: Please confirm the following
      options:
        - label: I've searched existing issues for similar requests
          required: true
        - label: This is not a duplicate of an existing feature request
          required: true
        - label: I understand this may take time to implement
          required: true
        - label: I'm open to contributing this feature myself
          required: false
